import { AnimationContainer, SectionContainer } from '@/components';
import { HeroSection } from '@/components/sections';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service for Spiderly - Review the terms and conditions for using Spiderly as a development tool.',
};

const TermsOfServicePage = () => {
  return (
    <div className="mb-3">
      <HeroSection
        title="Terms of Service"
        description="Review the terms and conditions for using Spiderly as a development tool."
      />

      <SectionContainer>
        <AnimationContainer>
          <div className="max-w-4xl mx-auto w-full prose prose-invert prose-p:text-muted-foreground prose-li:text-muted-foreground">
            <p className="text-sm text-muted-foreground">
              <strong>Effective Date:</strong> January 13, 2026
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using Spiderly (the &quot;Library&quot;), you agree to
              be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these
              Terms, do not use the Library.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Spiderly is a free open-source code generation framework that helps developers create
              full-stack web applications using .NET (C#) and Angular. The Library operates as a
              development-time tool that generates source code based on your Entity Framework Core
              models and configuration.
            </p>

            <h2>3. License Grant</h2>
            <p>
              Spiderly is licensed under the MIT License. You are granted a perpetual, worldwide,
              non-exclusive, royalty-free license to use, copy, modify, merge, publish, distribute,
              sublicense, and/or sell copies of the Library, subject to the terms of the MIT License
              included with the Library.
            </p>

            <h2>4. Ownership of Generated Code</h2>
            <p>
              You retain full ownership and all rights to any code generated by Spiderly. The
              generated code is yours to use, modify, distribute, and commercialize without any
              restrictions or royalty obligations to the Library authors.
            </p>

            <h2>5. Use Restrictions</h2>
            <p>You agree to:</p>
            <ul>
              <li>Use the Library in compliance with all applicable laws and regulations</li>
              <li>
                Not use the Library to generate applications that violate intellectual property
                rights
              </li>
              <li>
                Not remove or modify any copyright, trademark, or other proprietary notices from the
                Library
              </li>
              <li>Not use the Library to create illegal, harmful, or malicious applications</li>
            </ul>

            <h2>6. Third-Party Services and Integrations</h2>
            <p>
              The Library may integrate with or generate code that uses third-party services
              including but not limited to:
            </p>
            <ul>
              <li>Google OAuth 2.0 for authentication</li>
              <li>Email service providers (SMTP)</li>
              <li>Cloud storage providers (Azure Blob Storage, AWS S3, Cloudinary)</li>
              <li>Database systems (SQL Server, PostgreSQL)</li>
              <li>Angular and related UI libraries (PrimeNG, Transloco)</li>
            </ul>
            <p>
              Your use of these third-party services is subject to their respective terms of service
              and privacy policies. You are responsible for configuring and using these services in
              compliance with their terms.
            </p>

            <h2>7. Developer Responsibilities</h2>
            <p>As a developer using Spiderly, you are responsible for:</p>
            <ul>
              <li>
                Ensuring applications you generate comply with applicable privacy laws (GDPR, CCPA,
                etc.)
              </li>
              <li>Implementing appropriate security measures in your applications</li>
              <li>
                Creating and maintaining your own Terms of Service and Privacy Policy for end users
              </li>
              <li>Properly configuring authentication, authorization, and data storage</li>
              <li>Managing sensitive credentials (API keys, database passwords, OAuth secrets)</li>
              <li>Testing and validating generated code before deployment</li>
            </ul>

            <h2>8. Disclaimer of Warranties</h2>
            <p>
              THE LIBRARY IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
              IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, AND NONINFRINGEMENT. THE AUTHORS OR COPYRIGHT HOLDERS SHALL NOT BE
              LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY ARISING FROM THE USE OF THE LIBRARY.
            </p>
            <p>You acknowledge that:</p>
            <ul>
              <li>Generated code should be reviewed and tested before production use</li>
              <li>The Library may contain bugs or errors</li>
              <li>The Library authors do not guarantee compatibility with all environments</li>
              <li>Future updates may introduce breaking changes</li>
            </ul>

            <h2>9. Limitation of Liability</h2>
            <p>
              IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT,
              INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
              TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
              BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
              CONTRACT, STRICT LIABILITY, OR TORT ARISING OUT OF THE USE OF THE LIBRARY.
            </p>

            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless the Library authors, contributors, and
              maintainers from any claims, damages, losses, liabilities, and expenses (including
              reasonable attorney fees) arising from:
            </p>
            <ul>
              <li>Your use of the Library</li>
              <li>Applications you create using the Library</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights</li>
            </ul>

            <h2>11. Security and Data Handling</h2>
            <p>
              While the Library includes security features (JWT authentication, email verification,
              IP tracking, etc.), you acknowledge that:
            </p>
            <ul>
              <li>Security of generated applications is your responsibility</li>
              <li>You must properly configure and maintain security settings</li>
              <li>
                The Library does not collect or transmit your source code or data to external
                servers
              </li>
              <li>You are responsible for securing sensitive configuration data</li>
            </ul>

            <h2>12. Updates and Modifications</h2>
            <p>The Library may be updated periodically. Updates may:</p>
            <ul>
              <li>Add new features or capabilities</li>
              <li>Fix bugs or security vulnerabilities</li>
              <li>Introduce breaking changes requiring code modifications</li>
              <li>Deprecate or remove features</li>
            </ul>
            <p>
              You are responsible for reviewing release notes and testing updates before deployment.
            </p>

            <h2>13. Open Source Contributions</h2>
            <p>If you contribute code, documentation, or other materials to the Library:</p>
            <ul>
              <li>Your contributions will be licensed under the same MIT License</li>
              <li>You represent that you have the right to submit the contribution</li>
              <li>
                You grant the Library maintainers a perpetual license to use your contribution
              </li>
            </ul>

            <h2>14. Commercial Use</h2>
            <p>You may use the Library for commercial purposes, including:</p>
            <ul>
              <li>Building commercial applications</li>
              <li>Offering services based on generated code</li>
              <li>Distributing applications built with the Library</li>
            </ul>
            <p>
              No additional licenses or fees are required for commercial use under the MIT License.
            </p>

            <h2>15. Export Compliance</h2>
            <p>
              You agree to comply with all applicable export and import laws and regulations. You
              represent that you are not located in a country subject to embargo or identified as a
              &quot;terrorist supporting&quot; country, and that you are not on any government list
              of prohibited or restricted parties.
            </p>

            <h2>16. Termination</h2>
            <p>
              These Terms remain in effect until terminated. Your rights under these Terms will
              terminate automatically if you fail to comply with any provision. Upon termination:
            </p>
            <ul>
              <li>You must cease all use of the Library</li>
              <li>You may continue to use code previously generated (as you own that code)</li>
              <li>
                Provisions regarding ownership, disclaimers, and limitations of liability survive
                termination
              </li>
            </ul>

            <h2>17. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              jurisdiction in which the Library maintainers reside, without regard to conflict of
              law principles.
            </p>

            <h2>18. Entire Agreement</h2>
            <p>
              These Terms, together with the MIT License, constitute the entire agreement between
              you and the Library authors regarding the use of the Library and supersede all prior
              agreements and understandings.
            </p>

            <h2>19. Changes to Terms</h2>
            <p>
              The Library maintainers reserve the right to modify these Terms at any time. Changes
              will be effective upon posting to the Library&apos;s repository. Your continued use of
              the Library after changes are posted constitutes acceptance of the modified Terms.
            </p>

            <h2>20. Contact Information</h2>
            <p>
              For questions about these Terms, please open an issue on the Library&apos;s GitHub
              repository or contact the maintainers through the channels listed in the repository.
            </p>

            <h2>21. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable or invalid, that
              provision will be limited or eliminated to the minimum extent necessary, and the
              remaining provisions will remain in full force and effect.
            </p>

            <h2>22. No Waiver</h2>
            <p>
              The failure of the Library authors to enforce any right or provision of these Terms
              will not constitute a waiver of such right or provision.
            </p>

            <hr className="my-8" />

            <h2>MIT License Notice</h2>
            <p>Copyright (c) 2026 Spiderly Contributors</p>
            <p>
              Permission is hereby granted, free of charge, to any person obtaining a copy of this
              software and associated documentation files (the &quot;Software&quot;), to deal in the
              Software without restriction, including without limitation the rights to use, copy,
              modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
              and to permit persons to whom the Software is furnished to do so, subject to the
              following conditions:
            </p>
            <p>
              The above copyright notice and this permission notice shall be included in all copies
              or substantial portions of the Software.
            </p>
            <p>
              THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
              IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
              HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
              CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
              OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
            </p>

            <hr className="my-8" />

            <p className="text-sm text-muted-foreground">
              <strong>Last Updated:</strong> January 13, 2026
            </p>
            <p className="text-sm text-muted-foreground">
              <strong>Version:</strong> 1.0
            </p>
          </div>
        </AnimationContainer>
      </SectionContainer>
    </div>
  );
};

export default TermsOfServicePage;
